
site_name: noko1024

theme:
  name: material
  language: ja
  logo: https://github.com/noko1024.png
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.footer
    - toc.integrate
  font:
    text: Kosugi Maru

extra_css:
  - stylesheets/extra.css



markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.caret
